### ISSUE TITLE
Dropping records on AWS Errors

### ISSUE THREAD

**Issue by harlow** [tj/go-kinesis#4]
@tj I'm not sure if this is the intended behavior, but the producer drops the records when an AWS error occurs (i.e. it doesn't retry the records):

https://github.com/tj/go-kinesis/blob/master/kinesis.go#L182

**Comment by tj** [comment]
hmm I swear I read in the SDK that they have retry logic, could be wrong! (didn't end up using Kinesis in my current project)

**Comment by harlow** [comment]
> hmm I swear I read in the SDK that they have retry logic

Yep, so there will be a pre-determined number of retries for the Kinesis client:

https://github.com/aws/aws-sdk-go/blob/8599e6eb35d197b5bffb2944a09c55480b829c0f/aws/config.go#L65-L67

It can also be set manually: 

``` go
svc := kinesis.New(session.New(aws.NewConfig().WithMaxRetries(10)))
```

The broader question would be whether the records should be dropped when the AWS SDK hits max attempts, or should the producer determine when events are dropped based on `MaxAttempts`? Seems you may have already been thinking about that in https://github.com/tj/go-kinesis/issues/1 😉

**Comment by tj** [comment]
ah yes :D hahaha. Happy to add you as a collaborator BTW if you're interested. I do plan on using it, but that probably will be for the next project which could be a few months off

**Comment by harlow** [comment]
> Happy to add you as a collaborator BTW if you're interested

Sounds great 👍 . Be warned I may propose a few changes such as repo name, etc. 😸

**Comment by tj** [comment]
works for me! I have to stop naming them after the SDK names haha, I did that with the go-ses wrapper too, gets annoying
